[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@primuslabs/zktls-contracts=lib/zktls-contracts/src/"
]

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.monadexplorer.com/api" }